### ISSUE TITLE
npm run dev出错

### ISSUE THREAD

**Issue by ickedesign** [songhaoreact/vue-music#2]
以下是我`npm install`和`npm run dev`的结果，为什么出错了，麻烦指点以下，谢谢
```js
$ npm install

> fsevents@1.1.2 install F:\fontend_practice\originCode\vue-music\node_modules\fsevents
> node install

added 878 packages in 77.258s
```
``` js
$ npm run dev

> vue-music@1.0.0 dev F:\fontend_practice\originCode\vue-music
> node build/dev-server.js

npm WARN invalid config loglevel="notice"
> Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (F:\fontend_practice\originCode\vue-music\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (F:\fontend_practice\originCode\vue-music\build\dev-server.js:127:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-music@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-music@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bemiu\AppData\Roaming\npm-cache\_logs\2017-07-01T09_15_58_861Z-debug.log
```

**Comment by songhaoreact** [comment]
看样子是端口被占用了

**Comment by ickedesign** [comment]
是的。。还有我的npm升级到了5，所以这个版本有点坑。谢谢
